# Check https://circleci.com/docs/2.0/ for more details
# for config.yml syntax see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

executors:
  mac:
    macos:
      xcode: "10.1.0"

jobs:
  mac-test:
    executor: mac

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies for the app and for tests
      - restore_cache:
          keys:
          - dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-{{ arch }}-{{ .Branch }}-

      - run: npm install
      - run: npx cypress cache path

      - save_cache:
          paths:
            # local NPM modules
            - node_modules
            # all NPM modules
            - ~/.npm
            # Cypress binary (or yarn dependencies) on Linux
            - ~/Library/Caches/Cypress
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

      - run: $(npm bin)/commit-message-install --else "npm install cypress"
      - run: $(npm bin)/run-if npm run cypress:version
      - run: $(npm bin)/run-if npm run cypress:run
      - run: $(npm bin)/run-if npm run check-videos

  linux-test:
    docker:
      # find Docker image at https://github.com/cypress-io/cypress-docker-images
      - image: cypress/base:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies for the app and for tests
      - restore_cache:
          keys:
          - dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-{{ arch }}-{{ .Branch }}-

      - run: npm install

      - save_cache:
          paths:
            # local NPM modules
            - node_modules
            # all NPM modules
            - ~/.npm
            # Cypress binary (or yarn dependencies) on Linux
            - ~/.cache
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

      - run: $(npm bin)/commit-message-install --else "npm install cypress"
      - run: $(npm bin)/run-if npm run cypress:version
      - run: $(npm bin)/run-if npm run cypress:run
      - run: $(npm bin)/run-if npm run check-videos

workflows:
  version: 2
  tests:
    jobs:
      - linux-test
      - mac-test
